// params [title]
export const pieChart = {
    "data": [
        {
            "domain": {
                "x": [
                    0,
                    1
                ],
                "y": [
                    0,
                    1
                ]
            },
            "hovertemplate": "Gender=%{label}<br>ApplicantIncome=%{value}<extra></extra>",
            "labels": [
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                null,
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Female",
                "Female",
                "Female",
                "Female",
                "Female",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Female",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Female",
                "Male",
                "Female",
                "Female",
                "Male",
                "Male",
                "Female",
                null,
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                null,
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                null,
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Female",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Male",
                "Male",
                "Female",
                "Male",
                "Female",
                "Male",
                null,
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                null,
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Female",
                "Male",
                "Female",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                null,
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                null,
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                null,
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                null,
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Female",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Female",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                null,
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                null,
                "Male",
                "Male",
                "Male",
                null,
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                null,
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                null,
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Female",
                null,
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Female",
                "Female",
                "Male",
                "Male",
                "Female",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                null,
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Male",
                "Male",
                "Male",
                "Female",
                null,
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                null,
                "Male",
                "Female",
                "Female",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                null,
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Female",
                "Male",
                "Female",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Male",
                "Male",
                "Female",
                "Female",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Female",
                "Male",
                null,
                "Male",
                "Male",
                "Female",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Female",
                null,
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Female",
                null,
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Female",
                "Female",
                "Female",
                "Male",
                null,
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Female",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                null,
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Female",
                "Female",
                "Female",
                "Male",
                "Female",
                "Male",
                "Male",
                "Female",
                "Male",
                "Male",
                "Male",
                "Female"
            ],
            "legendgroup": "",
            "name": "",
            "showlegend": true,
            "values": [
                5849,
                4583,
                3000,
                2583,
                6000,
                5417,
                2333,
                3036,
                4006,
                12841,
                3200,
                2500,
                3073,
                1853,
                1299,
                4950,
                3596,
                3510,
                4887,
                2600,
                7660,
                5955,
                2600,
                3365,
                3717,
                9560,
                2799,
                4226,
                1442,
                3750,
                4166,
                3167,
                4692,
                3500,
                12500,
                2275,
                1828,
                3667,
                4166,
                3748,
                3600,
                1800,
                2400,
                3941,
                4695,
                3410,
                5649,
                5821,
                2645,
                4000,
                1928,
                3086,
                4230,
                4616,
                11500,
                2708,
                2132,
                3366,
                8080,
                3357,
                2500,
                3029,
                2609,
                4945,
                4166,
                5726,
                3200,
                10750,
                7100,
                4300,
                3208,
                1875,
                3500,
                4755,
                5266,
                3750,
                3750,
                1000,
                3167,
                3333,
                3846,
                2395,
                1378,
                6000,
                3988,
                2366,
                3333,
                2500,
                8566,
                5695,
                2958,
                6250,
                3273,
                4133,
                3620,
                6782,
                2484,
                1977,
                4188,
                1759,
                4288,
                4843,
                13650,
                4652,
                3816,
                3052,
                11417,
                7333,
                3800,
                2071,
                5316,
                2929,
                3572,
                7451,
                5050,
                14583,
                3167,
                2214,
                5568,
                10408,
                5667,
                4166,
                2137,
                2957,
                4300,
                3692,
                23803,
                3865,
                10513,
                6080,
                20166,
                2014,
                2718,
                3459,
                4895,
                4000,
                4583,
                3316,
                14999,
                4200,
                5042,
                5417,
                6950,
                2698,
                11757,
                2330,
                14866,
                1538,
                10000,
                4860,
                6277,
                2577,
                9166,
                2281,
                3254,
                39999,
                6000,
                9538,
                2980,
                4583,
                1863,
                7933,
                3089,
                4167,
                9323,
                3707,
                4583,
                2439,
                2237,
                8000,
                1820,
                51763,
                3522,
                5708,
                4344,
                3497,
                2045,
                5516,
                3750,
                2333,
                6400,
                1916,
                4600,
                33846,
                3625,
                39147,
                2178,
                2383,
                674,
                9328,
                4885,
                12000,
                6033,
                3858,
                4191,
                3125,
                8333,
                1907,
                3416,
                11000,
                2600,
                4923,
                3992,
                3500,
                3917,
                4408,
                3244,
                3975,
                2479,
                3418,
                10000,
                3430,
                7787,
                5703,
                3173,
                3850,
                150,
                3727,
                5000,
                4283,
                2221,
                4009,
                2971,
                7578,
                6250,
                3250,
                4735,
                6250,
                4758,
                6400,
                2491,
                3716,
                3189,
                8333,
                3155,
                5500,
                5746,
                3463,
                3812,
                3315,
                5819,
                2510,
                2965,
                6250,
                3406,
                6050,
                9703,
                6608,
                2882,
                1809,
                1668,
                3427,
                2583,
                2661,
                16250,
                3083,
                6045,
                5250,
                14683,
                4931,
                6083,
                2060,
                3481,
                7200,
                5166,
                4095,
                4708,
                4333,
                3418,
                2876,
                3237,
                11146,
                2833,
                2620,
                3900,
                2750,
                3993,
                3103,
                14583,
                4100,
                4053,
                3927,
                2301,
                1811,
                20667,
                3158,
                2600,
                3704,
                4124,
                9508,
                3075,
                4400,
                3153,
                5417,
                2383,
                4416,
                6875,
                4666,
                5000,
                2014,
                1800,
                2875,
                5000,
                1625,
                4000,
                2000,
                3762,
                2400,
                20233,
                7667,
                2917,
                2927,
                2507,
                5746,
                2473,
                3399,
                3717,
                2058,
                3541,
                10000,
                2400,
                4342,
                3601,
                3166,
                15000,
                8666,
                4917,
                5818,
                4333,
                2500,
                4384,
                2935,
                2833,
                63337,
                9833,
                5503,
                5250,
                2500,
                1830,
                4160,
                2647,
                2378,
                4554,
                3173,
                2583,
                2499,
                3523,
                3083,
                6333,
                2625,
                9083,
                8750,
                2666,
                5500,
                2423,
                3813,
                8333,
                3875,
                3000,
                5167,
                4723,
                5000,
                4750,
                3013,
                6822,
                6216,
                2500,
                5124,
                6325,
                19730,
                15759,
                5185,
                9323,
                3062,
                2764,
                4817,
                8750,
                4310,
                3069,
                5391,
                3333,
                5941,
                6000,
                7167,
                4566,
                3667,
                2346,
                3010,
                2333,
                5488,
                9167,
                9504,
                2583,
                1993,
                3100,
                3276,
                3180,
                3033,
                3902,
                1500,
                2889,
                2755,
                2500,
                1963,
                7441,
                4547,
                2167,
                2213,
                8300,
                81000,
                3867,
                6256,
                6096,
                2253,
                2149,
                2995,
                2600,
                1600,
                1025,
                3246,
                5829,
                2720,
                1820,
                7250,
                14880,
                2666,
                4606,
                5935,
                2920,
                2717,
                8624,
                6500,
                12876,
                2425,
                3750,
                10047,
                1926,
                2213,
                10416,
                7142,
                3660,
                7901,
                4707,
                37719,
                7333,
                3466,
                4652,
                3539,
                3340,
                2769,
                2309,
                1958,
                3948,
                2483,
                7085,
                3859,
                4301,
                3708,
                4354,
                8334,
                2083,
                7740,
                3015,
                5191,
                4166,
                6000,
                2947,
                16692,
                210,
                4333,
                3450,
                2653,
                4691,
                2500,
                5532,
                16525,
                6700,
                2873,
                16667,
                2947,
                4350,
                3095,
                2083,
                10833,
                8333,
                1958,
                3547,
                18333,
                4583,
                2435,
                2699,
                5333,
                3691,
                17263,
                3597,
                3326,
                2600,
                4625,
                2895,
                6283,
                645,
                3159,
                4865,
                4050,
                3814,
                3510,
                20833,
                3583,
                2479,
                13262,
                3598,
                6065,
                3283,
                2130,
                5815,
                3466,
                2031,
                3074,
                4683,
                3400,
                2192,
                2500,
                5677,
                7948,
                4680,
                17500,
                3775,
                5285,
                2679,
                6783,
                1025,
                4281,
                3588,
                11250,
                18165,
                2550,
                6133,
                3617,
                2917,
                6417,
                4608,
                2138,
                3652,
                2239,
                3017,
                2768,
                3358,
                2526,
                5000,
                2785,
                6633,
                2492,
                3333,
                2454,
                3593,
                5468,
                2667,
                10139,
                3887,
                4180,
                3675,
                19484,
                5923,
                5800,
                8799,
                4467,
                3333,
                3400,
                2378,
                3166,
                3417,
                5116,
                16666,
                6125,
                6406,
                3159,
                3087,
                3229,
                1782,
                3182,
                6540,
                1836,
                3166,
                1880,
                2787,
                4283,
                2297,
                2165,
                4750,
                2726,
                3000,
                6000,
                9357,
                3859,
                16120,
                3833,
                6383,
                2987,
                9963,
                5780,
                416,
                2894,
                5703,
                3676,
                12000,
                2400,
                3400,
                3987,
                3232,
                2900,
                4106,
                8072,
                7583,
                4583,
                5720,
                3076,
                5000,
                2340,
                3276,
                2165,
                2226,
                3881,
                13633,
                2400,
                3091,
                2185,
                4166,
                12173,
                4666,
                5667,
                4583,
                3786,
                9226,
                1300,
                1888,
                2083,
                3909,
                3765,
                5400,
                0,
                4363,
                7500,
                3772,
                2942,
                2478,
                6250,
                3268,
                2783,
                2740,
                3150,
                7350,
                2267,
                5833,
                3643,
                5629,
                3644,
                1750,
                6500,
                3666,
                4260,
                4163,
                2356,
                6792,
                8000,
                2419,
                3500,
                3500,
                4116,
                5293,
                2750,
                4402,
                3613,
                2779,
                4720,
                2415,
                7016,
                4968,
                2101,
                4490,
                2917,
                4700,
                3445,
                7666,
                2458,
                3250,
                4463,
                4083,
                3900,
                4750,
                3583,
                3189,
                6356,
                3413,
                7950,
                3829,
                72529,
                4136,
                8449,
                4456,
                4635,
                3571,
                3066,
                3235,
                5058,
                3188,
                13518,
                4364,
                4766,
                4609,
                6260,
                3333,
                3500,
                9719,
                6835,
                4452,
                2262,
                3901,
                2687,
                2243,
                3417,
                1596,
                4513,
                4500,
                4523,
                4742,
                4082,
                3417,
                2922,
                4167,
                4243,
                0,
                1516,
                1762,
                724,
                3125,
                2333,
                3350,
                2500,
                12500,
                4667,
                6500,
                7500,
                3073,
                3321,
                3333,
                3391,
                3343,
                3620,
                4000,
                4258,
                4500,
                2014,
                3333,
                4083,
                4727,
                3089,
                6794,
                32000,
                10890,
                12941,
                3276,
                8703,
                4742,
                5900,
                3071,
                2783,
                5000,
                2463,
                4855,
                1599,
                4246,
                4333,
                5823,
                7895,
                4150,
                2964,
                5583,
                2708,
                3180,
                2268,
                1141,
                3042,
                1750,
                3564,
                3958,
                4483,
                5225,
                3017,
                2431,
                4912,
                2500,
                2918,
                5128,
                15312,
                3958,
                4334,
                4358,
                4000,
                10166,
                4483,
                4521,
                9167,
                13083,
                7874,
                4333,
                4083,
                3785,
                2654,
                10000,
                5833,
                4796,
                2000,
                2540,
                1900,
                8706,
                2855,
                3016,
                3159,
                1937,
                2613,
                4960,
                3074,
                4213,
                2038,
                2362,
                5333,
                5384,
                5708,
                3754,
                2914,
                2747,
                7830,
                3507,
                3747,
                2166,
                3500,
                2896,
                5062,
                5184,
                2545,
                2553,
                3436,
                2412,
                5180,
                14911,
                2860,
                1173,
                7600,
                2157,
                2231,
                2274,
                6166,
                2513,
                4333,
                3844,
                3887,
                3510,
                2539,
                2107,
                3186,
                5000,
                10000,
                3943,
                2925,
                3242,
                3863,
                4028,
                4010,
                3719,
                2858,
                3833,
                3333,
                3007,
                1850,
                2792,
                2982,
                3417,
                18840,
                2995,
                3579,
                3835,
                3854,
                5833,
                3508,
                1635,
                3333,
                24797,
                5667,
                3500,
                2773,
                6500,
                5769,
                3634,
                29167,
                2166,
                5000,
                5530,
                9000,
                10000,
                8750,
                2157,
                1972,
                4983,
                8333,
                3667,
                3166,
                3271,
                2241,
                1792,
                2666,
                6478,
                3808,
                3729,
                4120,
                7500,
                6300,
                14987,
                570,
                2600,
                2733,
                7500,
                3859,
                6825,
                3708,
                5314,
                2366,
                2066,
                5000,
                3767,
                7859,
                4283,
                1700,
                4768,
                3083,
                2667,
                1647,
                3400,
                16000,
                5333,
                2875,
                2600,
                5041,
                6958,
                3500,
                5509,
                9699,
                3621,
                4709,
                1516,
                2400,
                3015,
                2292,
                2360,
                4333,
                2623,
                3972,
                3522,
                4700,
                6858,
                8334,
                3391,
                2868,
                3418,
                2500,
                8667,
                2283,
                5817,
                5119,
                5316,
                7603,
                3791,
                2500,
                3132,
                4000,
                8550,
                2269,
                4009,
                4158,
                3250,
                5000,
                9200,
                5769,
                3634,
                29167,
                2166,
                5000,
                16000,
                5333,
                2875,
                2600,
                5041,
                6958,
                5314,
                2366,
                2066,
                5000,
                3767,
                7441,
                4547,
                2167,
                2213,
                8300,
                81000,
                3867,
                6256,
                6096,
                2253,
                2149
            ],
            "type": "pie"
        }
    ],
    "layout": {
        "template": {
            "data": {
                "histogram2dcontour": [
                    {
                        "type": "histogram2dcontour",
                        "colorbar": {
                            "outlinewidth": 0,
                            "ticks": ""
                        },
                        "colorscale": [
                            [
                                0,
                                "#0d0887"
                            ],
                            [
                                0.1111111111111111,
                                "#46039f"
                            ],
                            [
                                0.2222222222222222,
                                "#7201a8"
                            ],
                            [
                                0.3333333333333333,
                                "#9c179e"
                            ],
                            [
                                0.4444444444444444,
                                "#bd3786"
                            ],
                            [
                                0.5555555555555556,
                                "#d8576b"
                            ],
                            [
                                0.6666666666666666,
                                "#ed7953"
                            ],
                            [
                                0.7777777777777778,
                                "#fb9f3a"
                            ],
                            [
                                0.8888888888888888,
                                "#fdca26"
                            ],
                            [
                                1,
                                "#f0f921"
                            ]
                        ]
                    }
                ],
                "choropleth": [
                    {
                        "type": "choropleth",
                        "colorbar": {
                            "outlinewidth": 0,
                            "ticks": ""
                        }
                    }
                ],
                "histogram2d": [
                    {
                        "type": "histogram2d",
                        "colorbar": {
                            "outlinewidth": 0,
                            "ticks": ""
                        },
                        "colorscale": [
                            [
                                0,
                                "#0d0887"
                            ],
                            [
                                0.1111111111111111,
                                "#46039f"
                            ],
                            [
                                0.2222222222222222,
                                "#7201a8"
                            ],
                            [
                                0.3333333333333333,
                                "#9c179e"
                            ],
                            [
                                0.4444444444444444,
                                "#bd3786"
                            ],
                            [
                                0.5555555555555556,
                                "#d8576b"
                            ],
                            [
                                0.6666666666666666,
                                "#ed7953"
                            ],
                            [
                                0.7777777777777778,
                                "#fb9f3a"
                            ],
                            [
                                0.8888888888888888,
                                "#fdca26"
                            ],
                            [
                                1,
                                "#f0f921"
                            ]
                        ]
                    }
                ],
                "heatmap": [
                    {
                        "type": "heatmap",
                        "colorbar": {
                            "outlinewidth": 0,
                            "ticks": ""
                        },
                        "colorscale": [
                            [
                                0,
                                "#0d0887"
                            ],
                            [
                                0.1111111111111111,
                                "#46039f"
                            ],
                            [
                                0.2222222222222222,
                                "#7201a8"
                            ],
                            [
                                0.3333333333333333,
                                "#9c179e"
                            ],
                            [
                                0.4444444444444444,
                                "#bd3786"
                            ],
                            [
                                0.5555555555555556,
                                "#d8576b"
                            ],
                            [
                                0.6666666666666666,
                                "#ed7953"
                            ],
                            [
                                0.7777777777777778,
                                "#fb9f3a"
                            ],
                            [
                                0.8888888888888888,
                                "#fdca26"
                            ],
                            [
                                1,
                                "#f0f921"
                            ]
                        ]
                    }
                ],
                "heatmapgl": [
                    {
                        "type": "heatmapgl",
                        "colorbar": {
                            "outlinewidth": 0,
                            "ticks": ""
                        },
                        "colorscale": [
                            [
                                0,
                                "#0d0887"
                            ],
                            [
                                0.1111111111111111,
                                "#46039f"
                            ],
                            [
                                0.2222222222222222,
                                "#7201a8"
                            ],
                            [
                                0.3333333333333333,
                                "#9c179e"
                            ],
                            [
                                0.4444444444444444,
                                "#bd3786"
                            ],
                            [
                                0.5555555555555556,
                                "#d8576b"
                            ],
                            [
                                0.6666666666666666,
                                "#ed7953"
                            ],
                            [
                                0.7777777777777778,
                                "#fb9f3a"
                            ],
                            [
                                0.8888888888888888,
                                "#fdca26"
                            ],
                            [
                                1,
                                "#f0f921"
                            ]
                        ]
                    }
                ],
                "contourcarpet": [
                    {
                        "type": "contourcarpet",
                        "colorbar": {
                            "outlinewidth": 0,
                            "ticks": ""
                        }
                    }
                ],
                "contour": [
                    {
                        "type": "contour",
                        "colorbar": {
                            "outlinewidth": 0,
                            "ticks": ""
                        },
                        "colorscale": [
                            [
                                0,
                                "#0d0887"
                            ],
                            [
                                0.1111111111111111,
                                "#46039f"
                            ],
                            [
                                0.2222222222222222,
                                "#7201a8"
                            ],
                            [
                                0.3333333333333333,
                                "#9c179e"
                            ],
                            [
                                0.4444444444444444,
                                "#bd3786"
                            ],
                            [
                                0.5555555555555556,
                                "#d8576b"
                            ],
                            [
                                0.6666666666666666,
                                "#ed7953"
                            ],
                            [
                                0.7777777777777778,
                                "#fb9f3a"
                            ],
                            [
                                0.8888888888888888,
                                "#fdca26"
                            ],
                            [
                                1,
                                "#f0f921"
                            ]
                        ]
                    }
                ],
                "surface": [
                    {
                        "type": "surface",
                        "colorbar": {
                            "outlinewidth": 0,
                            "ticks": ""
                        },
                        "colorscale": [
                            [
                                0,
                                "#0d0887"
                            ],
                            [
                                0.1111111111111111,
                                "#46039f"
                            ],
                            [
                                0.2222222222222222,
                                "#7201a8"
                            ],
                            [
                                0.3333333333333333,
                                "#9c179e"
                            ],
                            [
                                0.4444444444444444,
                                "#bd3786"
                            ],
                            [
                                0.5555555555555556,
                                "#d8576b"
                            ],
                            [
                                0.6666666666666666,
                                "#ed7953"
                            ],
                            [
                                0.7777777777777778,
                                "#fb9f3a"
                            ],
                            [
                                0.8888888888888888,
                                "#fdca26"
                            ],
                            [
                                1,
                                "#f0f921"
                            ]
                        ]
                    }
                ],
                "mesh3d": [
                    {
                        "type": "mesh3d",
                        "colorbar": {
                            "outlinewidth": 0,
                            "ticks": ""
                        }
                    }
                ],
                "scatter": [
                    {
                        "fillpattern": {
                            "fillmode": "overlay",
                            "size": 10,
                            "solidity": 0.2
                        },
                        "type": "scatter"
                    }
                ],
                "parcoords": [
                    {
                        "type": "parcoords",
                        "line": {
                            "colorbar": {
                                "outlinewidth": 0,
                                "ticks": ""
                            }
                        }
                    }
                ],
                "scatterpolargl": [
                    {
                        "type": "scatterpolargl",
                        "marker": {
                            "colorbar": {
                                "outlinewidth": 0,
                                "ticks": ""
                            }
                        }
                    }
                ],
                "bar": [
                    {
                        "error_x": {
                            "color": "#2a3f5f"
                        },
                        "error_y": {
                            "color": "#2a3f5f"
                        },
                        "marker": {
                            "line": {
                                "color": "#E5ECF6",
                                "width": 0.5
                            },
                            "pattern": {
                                "fillmode": "overlay",
                                "size": 10,
                                "solidity": 0.2
                            }
                        },
                        "type": "bar"
                    }
                ],
                "scattergeo": [
                    {
                        "type": "scattergeo",
                        "marker": {
                            "colorbar": {
                                "outlinewidth": 0,
                                "ticks": ""
                            }
                        }
                    }
                ],
                "scatterpolar": [
                    {
                        "type": "scatterpolar",
                        "marker": {
                            "colorbar": {
                                "outlinewidth": 0,
                                "ticks": ""
                            }
                        }
                    }
                ],
                "histogram": [
                    {
                        "marker": {
                            "pattern": {
                                "fillmode": "overlay",
                                "size": 10,
                                "solidity": 0.2
                            }
                        },
                        "type": "histogram"
                    }
                ],
                "scattergl": [
                    {
                        "type": "scattergl",
                        "marker": {
                            "colorbar": {
                                "outlinewidth": 0,
                                "ticks": ""
                            }
                        }
                    }
                ],
                "scatter3d": [
                    {
                        "type": "scatter3d",
                        "line": {
                            "colorbar": {
                                "outlinewidth": 0,
                                "ticks": ""
                            }
                        },
                        "marker": {
                            "colorbar": {
                                "outlinewidth": 0,
                                "ticks": ""
                            }
                        }
                    }
                ],
                "scattermapbox": [
                    {
                        "type": "scattermapbox",
                        "marker": {
                            "colorbar": {
                                "outlinewidth": 0,
                                "ticks": ""
                            }
                        }
                    }
                ],
                "scatterternary": [
                    {
                        "type": "scatterternary",
                        "marker": {
                            "colorbar": {
                                "outlinewidth": 0,
                                "ticks": ""
                            }
                        }
                    }
                ],
                "scattercarpet": [
                    {
                        "type": "scattercarpet",
                        "marker": {
                            "colorbar": {
                                "outlinewidth": 0,
                                "ticks": ""
                            }
                        }
                    }
                ],
                "carpet": [
                    {
                        "aaxis": {
                            "endlinecolor": "#2a3f5f",
                            "gridcolor": "white",
                            "linecolor": "white",
                            "minorgridcolor": "white",
                            "startlinecolor": "#2a3f5f"
                        },
                        "baxis": {
                            "endlinecolor": "#2a3f5f",
                            "gridcolor": "white",
                            "linecolor": "white",
                            "minorgridcolor": "white",
                            "startlinecolor": "#2a3f5f"
                        },
                        "type": "carpet"
                    }
                ],
                "table": [
                    {
                        "cells": {
                            "fill": {
                                "color": "#EBF0F8"
                            },
                            "line": {
                                "color": "white"
                            }
                        },
                        "header": {
                            "fill": {
                                "color": "#C8D4E3"
                            },
                            "line": {
                                "color": "white"
                            }
                        },
                        "type": "table"
                    }
                ],
                "barpolar": [
                    {
                        "marker": {
                            "line": {
                                "color": "#E5ECF6",
                                "width": 0.5
                            },
                            "pattern": {
                                "fillmode": "overlay",
                                "size": 10,
                                "solidity": 0.2
                            }
                        },
                        "type": "barpolar"
                    }
                ],
                "pie": [
                    {
                        "automargin": true,
                        "type": "pie"
                    }
                ]
            },
            "layout": {
                "autotypenumbers": "strict",
                "colorway": [
                    "#636efa",
                    "#EF553B",
                    "#00cc96",
                    "#ab63fa",
                    "#FFA15A",
                    "#19d3f3",
                    "#FF6692",
                    "#B6E880",
                    "#FF97FF",
                    "#FECB52"
                ],
                "font": {
                    "color": "#2a3f5f"
                },
                "hovermode": "closest",
                "hoverlabel": {
                    "align": "left"
                },
                "paper_bgcolor": "white",
                "plot_bgcolor": "#E5ECF6",
                "polar": {
                    "bgcolor": "#E5ECF6",
                    "angularaxis": {
                        "gridcolor": "white",
                        "linecolor": "white",
                        "ticks": ""
                    },
                    "radialaxis": {
                        "gridcolor": "white",
                        "linecolor": "white",
                        "ticks": ""
                    }
                },
                "ternary": {
                    "bgcolor": "#E5ECF6",
                    "aaxis": {
                        "gridcolor": "white",
                        "linecolor": "white",
                        "ticks": ""
                    },
                    "baxis": {
                        "gridcolor": "white",
                        "linecolor": "white",
                        "ticks": ""
                    },
                    "caxis": {
                        "gridcolor": "white",
                        "linecolor": "white",
                        "ticks": ""
                    }
                },
                "coloraxis": {
                    "colorbar": {
                        "outlinewidth": 0,
                        "ticks": ""
                    }
                },
                "colorscale": {
                    "sequential": [
                        [
                            0,
                            "#0d0887"
                        ],
                        [
                            0.1111111111111111,
                            "#46039f"
                        ],
                        [
                            0.2222222222222222,
                            "#7201a8"
                        ],
                        [
                            0.3333333333333333,
                            "#9c179e"
                        ],
                        [
                            0.4444444444444444,
                            "#bd3786"
                        ],
                        [
                            0.5555555555555556,
                            "#d8576b"
                        ],
                        [
                            0.6666666666666666,
                            "#ed7953"
                        ],
                        [
                            0.7777777777777778,
                            "#fb9f3a"
                        ],
                        [
                            0.8888888888888888,
                            "#fdca26"
                        ],
                        [
                            1,
                            "#f0f921"
                        ]
                    ],
                    "sequentialminus": [
                        [
                            0,
                            "#0d0887"
                        ],
                        [
                            0.1111111111111111,
                            "#46039f"
                        ],
                        [
                            0.2222222222222222,
                            "#7201a8"
                        ],
                        [
                            0.3333333333333333,
                            "#9c179e"
                        ],
                        [
                            0.4444444444444444,
                            "#bd3786"
                        ],
                        [
                            0.5555555555555556,
                            "#d8576b"
                        ],
                        [
                            0.6666666666666666,
                            "#ed7953"
                        ],
                        [
                            0.7777777777777778,
                            "#fb9f3a"
                        ],
                        [
                            0.8888888888888888,
                            "#fdca26"
                        ],
                        [
                            1,
                            "#f0f921"
                        ]
                    ],
                    "diverging": [
                        [
                            0,
                            "#8e0152"
                        ],
                        [
                            0.1,
                            "#c51b7d"
                        ],
                        [
                            0.2,
                            "#de77ae"
                        ],
                        [
                            0.3,
                            "#f1b6da"
                        ],
                        [
                            0.4,
                            "#fde0ef"
                        ],
                        [
                            0.5,
                            "#f7f7f7"
                        ],
                        [
                            0.6,
                            "#e6f5d0"
                        ],
                        [
                            0.7,
                            "#b8e186"
                        ],
                        [
                            0.8,
                            "#7fbc41"
                        ],
                        [
                            0.9,
                            "#4d9221"
                        ],
                        [
                            1,
                            "#276419"
                        ]
                    ]
                },
                "xaxis": {
                    "gridcolor": "white",
                    "linecolor": "white",
                    "ticks": "",
                    "title": {
                        "standoff": 15
                    },
                    "zerolinecolor": "white",
                    "automargin": true,
                    "zerolinewidth": 2
                },
                "yaxis": {
                    "gridcolor": "white",
                    "linecolor": "white",
                    "ticks": "",
                    "title": {
                        "standoff": 15
                    },
                    "zerolinecolor": "white",
                    "automargin": true,
                    "zerolinewidth": 2
                },
                "scene": {
                    "xaxis": {
                        "backgroundcolor": "#E5ECF6",
                        "gridcolor": "white",
                        "linecolor": "white",
                        "showbackground": true,
                        "ticks": "",
                        "zerolinecolor": "white",
                        "gridwidth": 2
                    },
                    "yaxis": {
                        "backgroundcolor": "#E5ECF6",
                        "gridcolor": "white",
                        "linecolor": "white",
                        "showbackground": true,
                        "ticks": "",
                        "zerolinecolor": "white",
                        "gridwidth": 2
                    },
                    "zaxis": {
                        "backgroundcolor": "#E5ECF6",
                        "gridcolor": "white",
                        "linecolor": "white",
                        "showbackground": true,
                        "ticks": "",
                        "zerolinecolor": "white",
                        "gridwidth": 2
                    }
                },
                "shapedefaults": {
                    "line": {
                        "color": "#2a3f5f"
                    }
                },
                "annotationdefaults": {
                    "arrowcolor": "#2a3f5f",
                    "arrowhead": 0,
                    "arrowwidth": 1
                },
                "geo": {
                    "bgcolor": "white",
                    "landcolor": "#E5ECF6",
                    "subunitcolor": "white",
                    "showland": true,
                    "showlakes": true,
                    "lakecolor": "white"
                },
                "title": {
                    "x": 0.05
                },
                "mapbox": {
                    "style": "light"
                }
            }
        },
        "legend": {
            "tracegroupgap": 0
        },
        "margin": {
            "t": 60
        },
        "title": {
            "text": "aaaaaaaa"
        }
    }
}